#!/usr/bin/env bash
set -euo pipefail

mkdir -p output

cat > matter_power.ini <<'EOF'
output = mPk
P_k_max_h/Mpc = 10

h = 0.6766
omega_b = 0.022382
omega_cdm = 0.12011
A_s = 2.105e-9
n_s = 0.9665
tau_reio = 0.0543


root = ./output/matter_
EOF

./class matter_power.ini
ls -lh output/
